const express=require('express'),http=require('http'),fs=require('fs'),path=require('path'),cors=require('cors'),cron=require('node-cron'),chokidar=require('chokidar')
const {Server}=require('socket.io'),db=require('./database')
const {runSync,stopSync,stopAllSyncs,getRunningJobs,getProgress,writeLog,isMountedPath,resetRuntimeState}=require('./sync')
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:'*'}})
const scheduledTasks=new Map(),watchers=new Map()
app.use(cors());app.use(express.json({limit:'10mb'}));app.use(express.static('public'))
function norm(p='/mnt'){let t=String(p||'/mnt').trim()||'/mnt';t=path.resolve(t);return t.startsWith('/mnt')?t:'/mnt'}
function listFolders(p){try{return fs.readdirSync(p,{withFileTypes:true}).filter(i=>i.isDirectory()).map(i=>{const full=path.join(p,i.name);return{name:i.name,path:full,mounted:isMountedPath(full)}}).sort((a,b)=>a.name.localeCompare(b.name))}catch{return[]}}
function suggest(q='/mnt'){const n=norm(q);let dir=n,part='';if(!fs.existsSync(n)){dir=path.dirname(n);part=path.basename(n).toLowerCase()}if(!dir.startsWith('/mnt'))dir='/mnt';return{query:q,current:dir,suggestions:listFolders(dir).filter(f=>f.name.toLowerCase().includes(part))}}
function validatePaths(source,destination){const src=norm(source),dst=norm(destination);if(!fs.existsSync(src))return{ok:false,error:`Source path does not exist: ${src}`};if(!fs.existsSync(dst))return{ok:false,error:`Destination/LAN path does not exist: ${dst}. Mount it first. The app will not create it.`};if(!isMountedPath(dst))return{ok:false,error:`Destination/LAN path is not on an active mount: ${dst}. Mount the LAN/NAS share first.`};try{fs.accessSync(src,fs.constants.R_OK);fs.accessSync(dst,fs.constants.R_OK|fs.constants.W_OK)}catch(e){return{ok:false,error:`Permission problem: ${e.message}`}}return{ok:true,source:src,destination:dst}}
function stopRuntime(id){const t=scheduledTasks.get(id);if(t){t.stop();scheduledTasks.delete(id)}const w=watchers.get(id);if(w){w.close();watchers.delete(id)}}
function startRuntime(job){stopRuntime(job.id);if(!job.enabled)return;if(job.schedule&&cron.validate(job.schedule)){const task=cron.schedule(job.schedule,()=>{const fresh=db.prepare('SELECT * FROM jobs WHERE id=?').get(job.id);if(fresh&&fresh.enabled)runSync(fresh,io,db)});scheduledTasks.set(job.id,task)}if(job.realtime){try{const watcher=chokidar.watch(job.source,{ignoreInitial:true,awaitWriteFinish:{stabilityThreshold:5000,pollInterval:1000},persistent:true,usePolling:true,interval:5000});let timer=null;watcher.on('all',()=>{clearTimeout(timer);timer=setTimeout(()=>{const fresh=db.prepare('SELECT * FROM jobs WHERE id=?').get(job.id);if(fresh&&fresh.enabled)runSync(fresh,io,db)},10000)});watcher.on('error',e=>writeLog(db,io,job,`Watcher error: ${e.message}`,'error'));watchers.set(job.id,watcher);writeLog(db,io,job,'Realtime watcher started')}catch(e){writeLog(db,io,job,`Could not start watcher: ${e.message}`,'error')}}}
function pub(job){return{name:job.name,source:job.source,destination:job.destination,schedule:job.schedule||'',schedule_label:job.schedule_label||'',realtime:!!job.realtime,mirror_delete:!!job.mirror_delete,enabled:!!job.enabled}}
function importJob(j){const chk=validatePaths(j.source,j.destination);if(!chk.ok)throw new Error(`${j.name||'Imported Job'}: ${chk.error}`);const sched=j.schedule||'';if(sched&&!cron.validate(sched))throw new Error(`Invalid cron schedule for job ${j.name||'Unnamed Job'}`);return{name:j.name||'Imported Job',source:chk.source,destination:chk.destination,schedule:sched,schedule_label:j.schedule_label||'',realtime:j.realtime?1:0,mirror_delete:j.mirror_delete?1:0,enabled:j.enabled===false?0:1}}
app.get('/api/health',(req,res)=>res.json({ok:true,running:getRunningJobs().length,uptime_seconds:Math.floor(process.uptime())}))
app.get('/api/browse',(req,res)=>{const cur=norm(req.query.path||'/mnt');res.json({current:cur,parent:cur==='/mnt'?null:path.dirname(cur),mounted:isMountedPath(cur),folders:listFolders(cur)})})
app.get('/api/suggest-path',(req,res)=>res.json(suggest(req.query.q||'/mnt')))
app.post('/api/validate-paths',(req,res)=>res.json(validatePaths(req.body.source,req.body.destination)))
app.get('/api/jobs',(req,res)=>res.json(db.prepare('SELECT * FROM jobs ORDER BY id DESC').all()))
app.post('/api/jobs',(req,res)=>{const chk=validatePaths(req.body.source,req.body.destination);if(!chk.ok)return res.status(400).json({error:chk.error});if(req.body.schedule&&!cron.validate(req.body.schedule))return res.status(400).json({error:'Invalid cron schedule'});const r=db.prepare('INSERT INTO jobs (name,source,destination,schedule,schedule_label,realtime,mirror_delete,enabled) VALUES (?,?,?,?,?,?,?,?)').run(req.body.name||'Mirror Job',chk.source,chk.destination,req.body.schedule||'',req.body.schedule_label||'',req.body.realtime?1:0,req.body.mirror_delete?1:0,1);const job=db.prepare('SELECT * FROM jobs WHERE id=?').get(r.lastInsertRowid);startRuntime(job);res.json({success:true,job})})
app.delete('/api/jobs/:id',(req,res)=>{const id=Number(req.params.id);stopSync(id,db,io);stopRuntime(id);db.prepare('DELETE FROM jobs WHERE id=?').run(id);res.json({success:true})})
app.post('/api/jobs/:id/run',(req,res)=>{const job=db.prepare('SELECT * FROM jobs WHERE id=?').get(req.params.id);if(!job)return res.status(404).json({error:'Job not found'});runSync(job,io,db);res.json({success:true})})
app.post('/api/jobs/:id/stop',(req,res)=>res.json({success:stopSync(req.params.id,db,io)}))
app.post('/api/stop-all',(req,res)=>res.json({success:true,stopped:stopAllSyncs(db,io)}))
app.get('/api/running',(req,res)=>res.json(getRunningJobs()))
app.get('/api/progress',(req,res)=>res.json(getProgress()))
app.get('/api/logs',(req,res)=>{const lim=Math.min(Number(req.query.limit||500),5000);res.json(db.prepare('SELECT * FROM job_logs ORDER BY id DESC LIMIT ?').all(lim).reverse())})
app.get('/api/jobs/:id/logs',(req,res)=>{const lim=Math.min(Number(req.query.limit||500),5000);res.json(db.prepare('SELECT * FROM job_logs WHERE job_id=? ORDER BY id DESC LIMIT ?').all(req.params.id,lim).reverse())})
app.delete('/api/logs',(req,res)=>{db.prepare('DELETE FROM job_logs').run();io.emit('logs-cleared');res.json({success:true})})
app.get('/api/export/jobs',(req,res)=>{const jobs=db.prepare('SELECT * FROM jobs ORDER BY id ASC').all().map(pub);res.setHeader('Content-Type','application/json');res.setHeader('Content-Disposition','attachment; filename="smb-mirror-jobs.json"');res.send(JSON.stringify({version:6,exported_at:new Date().toISOString(),jobs},null,2))})
app.get('/api/export/jobs/:id',(req,res)=>{const job=db.prepare('SELECT * FROM jobs WHERE id=?').get(req.params.id);if(!job)return res.status(404).json({error:'Job not found'});res.setHeader('Content-Type','application/json');res.setHeader('Content-Disposition',`attachment; filename="smb-mirror-job-${job.id}.json"`);res.send(JSON.stringify({version:6,exported_at:new Date().toISOString(),jobs:[pub(job)]},null,2))})
app.post('/api/import/jobs',(req,res)=>{try{const jobs=Array.isArray(req.body)?req.body:Array.isArray(req.body.jobs)?req.body.jobs:[req.body];const ids=[];const ins=db.prepare('INSERT INTO jobs (name,source,destination,schedule,schedule_label,realtime,mirror_delete,enabled) VALUES (?,?,?,?,?,?,?,?)');db.transaction(items=>{for(const raw of items){const j=importJob(raw);const r=ins.run(j.name,j.source,j.destination,j.schedule,j.schedule_label,j.realtime,j.mirror_delete,j.enabled);ids.push(r.lastInsertRowid)}})(jobs);const imported=ids.map(id=>db.prepare('SELECT * FROM jobs WHERE id=?').get(id));for(const j of imported)startRuntime(j);res.json({success:true,imported:imported.length,jobs:imported})}catch(e){res.status(400).json({error:e.message})}})
for(const sig of ['SIGTERM','SIGINT'])process.on(sig,()=>{stopAllSyncs(db,io);server.close(()=>process.exit(0))})
io.on('connection',s=>s.emit('log','Connected to SMB Mirror'))
resetRuntimeState(io);for(const job of db.prepare('SELECT * FROM jobs WHERE enabled=1').all())startRuntime(job)
const PORT=Number(process.env.PORT||5800);server.listen(PORT,()=>console.log(`SMB Mirror running on port ${PORT}`))
