const {spawn}=require('child_process')
const fs=require('fs'),path=require('path')
const runningJobs=new Map(),jobProgress=new Map()
function ensureMntPath(p){const r=path.resolve(p||'/mnt');if(!r.startsWith('/mnt'))throw new Error('Only paths inside /mnt are allowed');return r}
function isMountedPath(p){const r=ensureMntPath(p);const txt=fs.readFileSync('/proc/mounts','utf8');return txt.split('\n').map(l=>l.split(' ')[1]).filter(Boolean).map(m=>m.replace(/\\040/g,' ')).some(m=>m!=='/mnt'&&(r===m||r.startsWith(m+'/')))}
function validateDir(label,p,requireMounted=false,write=false){const r=ensureMntPath(p);if(!fs.existsSync(r))throw new Error(`${label} path does not exist: ${r}. Mount it on the host first.`);if(!fs.statSync(r).isDirectory())throw new Error(`${label} path is not a folder: ${r}`);fs.accessSync(r,write?(fs.constants.R_OK|fs.constants.W_OK):fs.constants.R_OK);if(requireMounted&&!isMountedPath(r))throw new Error(`${label} path is not on an active mounted drive/share: ${r}. The app will not create missing LAN/NAS folders under /mnt.`);return r}
function writeLog(db,io,job,msg,level='info'){const text=`[${job.name}] ${msg}`;db.prepare('INSERT INTO job_logs (job_id,job_name,level,message) VALUES (?,?,?,?)').run(job.id,job.name,level,text);io.emit('log',text);io.emit('job-log',{job_id:job.id,job_name:job.name,level,message:text,created_at:new Date().toISOString()})}
function isNoisyRsyncLine(line){return line.includes('sending incremental file list')||line.startsWith('sent ')||line.startsWith('total size is ')||line.startsWith('./')}
function speedBps(t){if(!t)return 0;const m=t.match(/([\d.]+)\s*([KMGT]?B)\/s/i);if(!m)return 0;const v=Number(m[1]),u=m[2].toUpperCase(),x={B:1,KB:1024,MB:1048576,GB:1073741824,TB:1099511627776};return v*(x[u]||1)}
function parseProgress(line){const m=line.match(/([\d.,]+[KMGT]?B?)\s+(\d+)%\s+([\d.]+[KMGT]?B\/s)\s+([0-9:]+)/i);if(!m)return null;return{transferred_text:m[1],percent:Number(m[2]),speed_text:m[3],speed_bps:speedBps(m[3]),eta:m[4]}}
function setProgress(io,job,patch){const cur=jobProgress.get(job.id)||{job_id:job.id,job_name:job.name,source:job.source,destination:job.destination,current_file:'',overall_percent:0,transferred_text:'',speed_text:'',speed_bps:0,eta:'',status:'running',mirror_delete:!!job.mirror_delete,started_at:new Date().toISOString()};const next={...cur,...patch,updated_at:new Date().toISOString()};jobProgress.set(job.id,next);io.emit('progress',next);io.emit('running-jobs-changed')}
function killGroup(proc){if(!proc||!proc.pid)return;try{process.kill(-proc.pid,'SIGTERM')}catch{}setTimeout(()=>{try{process.kill(-proc.pid,'SIGKILL')}catch{}},5000)}
function cleanup(jobId,io,patch={}){const r=runningJobs.get(Number(jobId));runningJobs.delete(Number(jobId));if(r?.watchdog)clearTimeout(r.watchdog);if(r?.quietWatchdog)clearInterval(r.quietWatchdog);if(r?.job)setProgress(io,r.job,patch)}
function stopSync(jobId,db,io){const r=runningJobs.get(Number(jobId));if(!r)return false;writeLog(db,io,r.job,'Force stop requested. Terminating rsync process group...','warn');setProgress(io,r.job,{status:'stopping'});killGroup(r.proc);return true}
function stopAllSyncs(db,io){let c=0;for(const id of runningJobs.keys())if(stopSync(id,db,io))c++;return c}
async function runSync(job,io,db){if(runningJobs.has(job.id)){writeLog(db,io,job,'Copy already running, skipping duplicate request','warn');return}let proc=null;try{const source=validateDir('Source',job.source,false,false),dest=validateDir('Destination/LAN',job.destination,true,true);setProgress(io,job,{status:'running',mirror_delete:!!job.mirror_delete,current_file:job.mirror_delete?'Scanning for changes and destination-only files...':'Scanning for missing files only...',overall_percent:0,transferred_text:'',speed_text:'',speed_bps:0,eta:''});writeLog(db,io,job,job.mirror_delete?'Starting MIRROR mode. Destination-only files may be deleted.':'Starting SAFE mode. Copy missing files only; no deletes/replacements.');writeLog(db,io,job,`Source: ${source}`);writeLog(db,io,job,`Destination: ${dest}`)
const args=['-rvh','--progress','--info=progress2,name1','--human-readable','--no-perms','--no-owner','--no-group','--omit-dir-times','--modify-window=2'];if(job.mirror_delete)args.push('--delete');else args.push('--ignore-existing');args.push(`${source}/`,`${dest}/`)
proc=spawn('rsync',args,{detached:true,stdio:['ignore','pipe','pipe']});let last=Date.now();const max=Number(process.env.MAX_JOB_RUNTIME_MINUTES||1440)*60000;const watchdog=setTimeout(()=>{if(runningJobs.has(job.id)){writeLog(db,io,job,'Max runtime reached. Stopping job.','warn');stopSync(job.id,db,io)}},max);const quietWatchdog=setInterval(()=>{if(runningJobs.has(job.id)){const mins=Math.floor((Date.now()-last)/60000);if(mins>=60)writeLog(db,io,job,`No rsync output for ${mins} minutes. Use Force Stop if needed.`,'warn')}},900000);runningJobs.set(job.id,{proc,job,watchdog,quietWatchdog})
proc.stdout.on('data',d=>{last=Date.now();for(const line of d.toString().split(/\r?\n/).map(s=>s.trim()).filter(Boolean)){const p=parseProgress(line);if(p){setProgress(io,job,{overall_percent:p.percent,transferred_text:p.transferred_text,speed_text:p.speed_text,speed_bps:p.speed_bps,eta:p.eta});continue}if(isNoisyRsyncLine(line))continue;setProgress(io,job,{current_file:line})}})
proc.stderr.on('data',d=>{last=Date.now();for(const line of d.toString().split('\n').filter(Boolean))writeLog(db,io,job,`ERROR: ${line}`,'error')})
proc.on('error',err=>{writeLog(db,io,job,`Process error: ${err.message}`,'error');cleanup(job.id,io,{status:'error',current_file:err.message})})
proc.on('exit',(code,signal)=>writeLog(db,io,job,`rsync exited with code ${code}, signal ${signal||'none'}`,code===0?'info':'warn'))
proc.on('close',code=>{writeLog(db,io,job,`Job finished with code ${code}`,code===0?'info':'error');cleanup(job.id,io,{status:code===0?'completed':'error',overall_percent:code===0?100:(jobProgress.get(job.id)?.overall_percent||0),speed_bps:0,speed_text:'',eta:''})});io.emit('running-jobs-changed')}catch(err){if(proc)killGroup(proc);runningJobs.delete(job.id);writeLog(db,io,job,err.message,'error');setProgress(io,job,{status:'error',current_file:err.message});io.emit('running-jobs-changed')}}
function getRunningJobs(){return Array.from(runningJobs.entries()).map(([id,v])=>({job_id:id,job_name:v.job.name,source:v.job.source,destination:v.job.destination}))}
function getProgress(){return Array.from(jobProgress.values())}
function resetRuntimeState(io){runningJobs.clear();for(const [id,p]of jobProgress.entries()){if(['running','stopping'].includes(p.status)){p.status='stale';p.speed_bps=0;p.speed_text='';p.eta='';jobProgress.set(id,p);io.emit('progress',p)}}}
module.exports={runSync,stopSync,stopAllSyncs,getRunningJobs,getProgress,writeLog,isMountedPath,resetRuntimeState}
